# Generated by Django 3.0.7 on 2020-10-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('fee', models.FloatField()),
                ('seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='img/trainers')),
            ],
        ),
    ]
