# Generated by Django 3.0.7 on 2020-10-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201029_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='trainer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer'),
        ),
    ]
