# Generated by Django 3.0.7 on 2020-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201030_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
