# Generated by Django 3.0.7 on 2020-10-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_course_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
